Feat/update
Team-INSERT/BUMAWIKI_WEB_V3 pull request #77
Opened 2024-03-16 14:32 UTC by 5ewon

## Issue Number
#76 
## What
문서수정페이지 구현했습니다.
## How
문서 수정, 수정 사항 되돌리기,  역사 페이지 인덱스 +1
## ScreenShot
![image](https://github.com/Team-INSERT/BUMAWIKI_WEB_V3/assets/101105694/ada58b7e-4c89-488b-b13f-41cfb17ff3fa)

2024-03-16 15:00 UTC, 5ewon commented
일단 기능 구현에만 초점을 두고 만들었습니다. 개선할 예정입니다.
🥵🤞

2024-03-16 15:24 UTC, Ubinquitous requested changes
수고하셨습니다!!
짧은 시간 내에 폭발적인 퍼포먼스를 보여주셔서 놀랐습니다!

2024-03-16 15:24 UTC, Ubinquitous commented on app/create/page.tsx
> +      <Editor isEdit={false} />
값을 전달하지않고 isEdit속성을 boolean | undefined로 설정하는게더낫지않을까요?

2024-03-16 15:24 UTC, Ubinquitous commented on app/edit/[title]/page.tsx
> +      <Editor content={doc.contents} title={doc.title} isEdit />
기왕이면 `content`, `contents`와같은 속성명은 맞춰주시는게좋을것같습니다!
그리고 확장성을 위해서 `{...docs}`와같이 써보시는건어떨까요?

2024-03-16 15:24 UTC, Ubinquitous commented on app/history/[title]/History.tsx
> +            <h1 className={styles.historyId}>#{history.index + 1}</h1>
history index는 백엔드기준 0부터시작해서 +1을 하지 않았었습니다..!!

2024-03-16 15:24 UTC, Ubinquitous commented on components/Editor/index.tsx
> +
`handleContentsUndoClick`은어떠신가요?
그리고 contents, content를 위에서말했던것과같이 속성명을 맞춰두면 구조분해할당을 할수있을것같습니다.
그리고 undo라는 네이밍과는 다르게 어떤 역할을 하는 함수인지를 잘모르겠습니다!

2024-03-16 15:24 UTC, Ubinquitous commented on components/Editor/index.tsx
> +  }, []);
useEffect말고 다른방법으로 디펜던시를 주입하는방법은 없을까요?
if문이나 함수등 이모저모 불편하고 렌더링도 추가될것같아요.
해당 함수를 삭제하고 useState의 docs에 contents와title을기본으로두고, 각 input과 textarea에 title, contents를 key로주어 렌더링을 제어하는건 어떠신가요?

2024-03-16 15:24 UTC, Ubinquitous commented on components/Editor/index.tsx
> +          )}
`{!isEdit && <div></div>}`와같은형태는 어떠신가요?

2024-03-16 15:24 UTC, Ubinquitous commented on components/Editor/index.tsx
> +                되돌리기
되돌리기기능 좋은것같네요!! 그런데 이 함수를 트리거할때도 alert나confirm등의 중간작업이있으면 실수로초기화하는 일이 없을것같습니다!

2024-03-16 15:24 UTC, Ubinquitous commented on services/docs/docs.api.ts
> +    { contents: content },
마찬가지로 contents라는 네이밍을주어서 구조분해할당하면 콜론을 사용하지않고 값을주입해줄수있을것같습니다!

2024-03-16 15:40 UTC, 5ewon commented on components/Editor/index.tsx
> +                되돌리기
이번 modal PR 머지 이후 적용시켜보겠습니다.

2024-03-16 15:41 UTC, 5ewon commented on components/Editor/index.tsx
> +          )}
확실히 단순 빈 문자열보단 빈태그라도 주면 더 깔끔하고 추후 정렬에서도 도움이 더 될 것같네요

2024-03-16 15:41 UTC, 5ewon commented on components/Editor/index.tsx
> +  }, []);
좋은 의견 감사합니다! 반영해보겠습니다.

2024-03-16 15:43 UTC, 5ewon commented on app/history/[title]/History.tsx
> +            <h1 className={styles.historyId}>#{history.index + 1}</h1>
유저는 모를 가능성이 있다고 생각해서 바꿔봤습니다. 하지만 나름 다 이유가 있었군요.

2024-03-16 15:43 UTC, 5ewon commented on app/edit/[title]/page.tsx
> +      <Editor content={doc.contents} title={doc.title} isEdit />
확실히 속명명을 통일 시키면 파라미터 전달에서도 유리할 것 같네요! 두가지 다 반영하겠습니다.

2024-03-16 15:44 UTC, 5ewon commented on app/create/page.tsx
> +      <Editor isEdit={false} />
이게 더 명시적이지 않을까 싶었습니다. 하지만 우빈님 의견이 코드상으로 더 깔끔할 것 같네요

2024-03-16 15:45 UTC, 5ewon commented on services/docs/docs.api.ts
> +    { contents: content },
props 타입에 대해서는 어떻게 생각하는지 궁금합니다. 임시로 일단 저렇게 지정해놨는데 interface로 따로 빼는게 좋을까요?

2024-03-16 16:01 UTC, Ubinquitous commented on services/docs/docs.api.ts
> +    { contents: content },
저는 이번 컨벤션에서는 그대로 가도 괜찮을것같다고 생각합니다!
api 함수만 모여있는상태에서 바로위에 인터페이스를 정의하기도 애매하고, 모듈화하기도 애매해서
2개 이하의 객체는 묵시적으로 지정해주어도 좋을것같아요 !

2024-03-16 16:02 UTC, Ubinquitous commented on app/create/page.tsx
> +      <Editor isEdit={false} />
만약 명시적으로 코드를 작성하고 싶으시다면 `{ mode: "edit" | "create" }`와 같이 props를 변경하는것도 괜찮을것같습니다!

2024-03-16 16:03 UTC, Ubinquitous commented on app/history/[title]/History.tsx
> +            <h1 className={styles.historyId}>#{history.index + 1}</h1>
말씀하신 유저플로우가 더욱 와닿는다면 그대로가고, 히스토리 디테일에서 `받은값-1`로 get하는 방법도 있습니다!
저는 듣고보니 1부터시작하는게 조금더 자연스러울것같다고 생각하긴했습니다!

2024-03-16 16:04 UTC, Ubinquitous commented on components/Editor/index.tsx
> +          )}
삼항연산자를 조건부렌더링으로 바꾸는 것에 대해 말씀드린거였습니다! 제가 설명이좀부족했네요😀

2024-03-17 02:50 UTC, 5ewon commented on components/Editor/index.tsx
> +          )}
어제 너무 잠이 와서 잘못 읽었나봅니다. 설명에 부족한 점은 없었습니다!

2024-03-17 05:30 UTC, Ubinquitous approved these changes
good

2024-03-17 05:31 UTC, merged